---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: blog-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-image-repository
  policy:
    semver:
      range: 0.0.x

