apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: blog
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: blog
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: blog
  name: blog
  namespace: default
spec:
  containers:
  - image: ghcr.io/mharikmert/blog:v0.0.11
    name: blog
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
