apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
        app: blog
    template:
        metadata:
        labels:
            app: blog
        spec:
          - name: blog
            containers:
            image: ghcr.io/mharikmert/blog:v0.0.11
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: default
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
    selector:
        app: blog
